name: PR Review

on:
  pull_request:
    types:
      - edited
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 15.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
